Configured for CentOS and put a basic config in with the ssl settings

diff --git a/redhat/etherpad.init b/redhat/etherpad.init
--- a/redhat/etherpad.init
+++ b/redhat/etherpad.init
@@ -1,101 +1,178 @@
 #!/bin/bash
 #
-# etherpad        Startup script for Etherpad
+# Configurable init.d script
 #
-# chkconfig: 345 99 01
-# description: Collaborative real-time editor
+# chkconfig: 345 20 80
+# description: Runs Etherpad
 # processname: etherpad
-# config: /etc/sysconfig/etherpad
-# config: ${ETHERPAD_HOME}/etherpad/etc/etherpad.local.propeties
-# pidfile: /var/run/etherpad/etherpad.pid
-# pidfile: /var/run/etherpad/soffice.pid
 
-# Source function library.
-. /etc/init.d/functions
+###### SCRIPT CONFIG ######
+# Script to run as service:
+START_SCRIPT="/home/etherpad/pad/bin/run.sh"  # Or command for testing
 
-# Load Environment Variables.
-if [ -f /etc/sysconfig/etherpad ]; then
-        . /etc/sysconfig/etherpad
+# User to run script under
+USER="etherpad"  # Can be any user - init runs as root, best for the script not to
+
+###### END SCRIPT CONFIG ######
+
+
+NAME="$(basename $0)"
+unset ISBOOT
+if [ "${NAME:0:1}" = "S" -o "${NAME:0:1}" = "K" ]; then
+    NAME="${NAME:3}"
+    ISBOOT="1"
 fi
 
-CP="appjet-eth-dev.jar:data"
-for f in $ETHERPAD_HOME/etherpad/lib/*.jar; do
-        CP="$CP:$f"
-done
+# For SELinux we need to use 'runuser' not 'su'
+if [ -x "/sbin/runuser" ]; then
+    SU="/sbin/runuser"
+else
+    SU="su"
+fi
 
-sname="soffice"
-slockfile="/var/lock/subsys/${sname}"
-spidfile="${PID_HOME}/${sname}.pid"
-slogfile="/var/log/${sname}.log"
-sargs="-nologo -nofirststartwizard -headless -norestore -invisible \"-accept=socket,host=localhost,port=8100;urp;StarOffice.Service\""
+LOCKFILE="/var/lock/subsys/${NAME}"
+RETVAL="0"
 
-ename="etherpad"
-elockfile="/var/lock/subsys/${ename}"
-epidfile="${PID_HOME}/${ename}.pid"
-elogfile="/var/log/${ename}.log"
-eargs="-classpath ${CP} -server -Xmx${MAXRAM} -Xms${MAXRAM} -Djava.awt.headless=true -XX:MaxGCPauseMillis=500 -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:CMSIncrementalSafetyFactor=50 -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -Xloggc:./data/logs/backend/jvm-gc.log -Dappjet.jmxremote=true net.appjet.oui.main --configFile=${ETHERPAD_CONFIG} --maxThreads=${MAXTHREADS}"
-
-start() {
-        echo "Starting ${sname}: "
-        ( daemon --user=etherpad ${OOFFICE} ${sargs} >> ${slogfile} ) &
-	[ "$VERBOSE" != no ] && echo -n "Waiting for service to come up ..."
-        for counter in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
-                fuser -n tcp 8100 > /dev/null 2>&1 && break
-                [ "$VERBOSE" != no ] && echo -n "."
-                sleep 1
-        done
-        [ "$VERBOSE" != no ] && echo ""
-	pgrep -U etherpad soffice >> ${spidfile}
-
-	echo "Starting ${ename}: "
-	( daemon --user=etherpad ${JAVA} "${eargs}" >> ${elogfile} ) &
-	[ "$VERBOSE" != no ] && echo -n "Waiting for service to come up ..."
-        for counter in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
-                echo "GET /" | netcat -w 1 localhost 9000 > /dev/null 2>&1 && break
-                [ "$VERBOSE" != no ] && echo -n "."
-                sleep 1
-        done
-        [ "$VERBOSE" != no ] && echo ""
-	pgrep -U etherpad java >> ${epidfile}
-	RETVAL=$?
-	touch ${slockfile}
-	touch ${elockfile}
-	echo "done"
+# remove when the RHEL and FC daemon functions converge
+# (pulled from /etc/rc.d/init.d/functions)
+function checkpid() {
+    local i
+    for i in $* ; do
+        if [ -d "/proc/${i}" ]; then
+            return 0
+        fi
+    done
+    return 1
 }
 
-stop() {
-	echo "Stopping ${sname}: "
-	killproc -p ${spidfile}
-	echo "Stopping ${ename}: "
-	killproc -d 30 -p ${epidfile}
-	RETVAL=$?
-	rm -f ${slockfile} ${spidfile} ${elockfile} ${epidfile}
+# remove when the RHEL and FC daemon functions converge
+# (pulled from /etc/rc.d/init.d/functions)
+function echo_failure() {
+    echo -en "\\033[60G"
+    echo -n "["
+    echo -en "\\033[0;31m"
+    echo -n $"FAILED"
+    echo -en "\\033[0;39m"
+    echo -n "]"
+    echo -ne "\r"
+    return 1
 }
-restart() {
-	stop
-	start
+
+# remove when the RHEL and FC daemon functions converge
+# (pulled from /etc/rc.d/init.d/functions)
+function echo_success() {
+    echo -en "\\033[60G"
+    echo -n "["
+    echo -en "\\033[0;32m"
+    echo -n $"  OK  "
+    echo -en "\\033[0;39m"
+    echo -n "]"
+    echo -ne "\r"
+    return 0
 }
 
 # See how we were called.
+function start() {
+    echo -n "Starting ${NAME}: "
+
+    if [ -e "${LOCKFILE}" ]; then
+	PID=`cat ${LOCKFILE}`
+	if ps -ef | awk '{ print $2 }' | grep $PID > /dev/null
+	then
+	    echo_failure
+	    return 1
+	else
+	    rm -f ${LOCKFILE}
+	fi
+    fi
+
+    $SU -s /bin/sh - $USER -c "$START_SCRIPT" 2>&1 > /dev/null &
+    PID="$!"
+    RETVAL="$?"
+    if [ "$RETVAL" -eq 0 ]; then
+        echo_success
+	echo "$PID" > ${LOCKFILE}
+    else
+        echo_failure
+    fi
+    echo
+    return $RETVAL
+}
+
+function status() {
+    RETVAL="1"
+
+    if [ -e "${LOCKFILE}" ]; then
+	PID=`cat ${LOCKFILE}`
+	if ps -ef | awk '{ print $2 }' | grep $PID > /dev/null
+        then
+	    echo "$NAME is running (${PID})"
+	    RETVAL="0"
+	else
+	    rm -f ${LOCKFILE}
+	    echo "$NAME is stopped"
+	fi
+    else
+	echo "$NAME is stopped"
+    fi
+
+   return $RETVAL
+}
+
+function stop() {
+    local STOP_VERBOSE="false"
+    RETVAL="1"
+    echo -n "Stopping $NAME: "
+
+    if [ -e "${LOCKFILE}" ]; then
+	PID=`cat ${LOCKFILE}`
+	if ps -ef | awk '{ print $2 }' | grep $PID > /dev/null
+	then
+            JAVA_PID=$(ps aux | grep ^etherpad | grep java | awk '{ print $2 }')
+            kill $JAVA_PID 2>&1 > /dev/null
+	    sleep 5
+	    RETVAL="0"
+	    echo_success
+	else
+	    echo_failure
+	fi
+
+	rm -f ${LOCKFILE}
+    else
+	echo_failure
+    fi
+
+    return $RETVAL
+}
+
+
+# See how we were called.
 case "$1" in
-  start)
-	start
-	;;
-  stop)
-	stop
-	;;
-  status)
-        echo -n ${sname} ;status -p ${spidfile}
-	echo -n ${ename} ;status -p ${epidfile}	
-	RETVAL=$?
-	;;
-  restart)
-	stop
-	start
-	;;
-  *)
-	echo $"Usage: $prog {start|stop|restart|status}"
-	exit 1
+    start)
+        start
+        ;;
+    stop)
+        stop
+        ;;
+    restart)
+        stop
+        sleep 2
+        start
+        ;;
+    condrestart)
+        if [ -f "${LOCKFILE}" ]; then
+            stop
+            start
+        fi
+        ;;
+    status)
+        status
+        ;;
+    *)
+        echo "Usage: $NAME {start|stop|restart|status}"
+        exit 1
 esac
 
 exit $RETVAL
+
+
